### ISSUE TITLE
Install SFTP client on laptop

### ISSUE THREAD

**Issue by Jual6332** [Jual6332/OTheRS_IP#3]
**Motivation:**
- Initial testing will produce 1.) temperature data 2.) image output. 
- This data needs to be transferred to the Pi from laptop to be accessible by image processing
- Secure File transfer protocol to connect Pi and laptop

One such SFTP client is FileZilla

SFTP Link: https://www.raspberrypi.org/documentation/remote-access/ssh/sftp.md
FileZilla Link and Steps: https://geek-university.com/raspberry-pi/use-sftp-to-transfer-files/

**Comment by Jkillelea** [comment]
If you're on a linux/mac system then it should have `sftp` by default. In debian the executable is in the `openssh-client` package.

**Comment by Jual6332** [comment]
Yes.
